[tool.poetry]
name = "stt"
version = "0.1.0"
description = ""
authors = ["Bassrelic"]
license = "mit"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
RealtimeSTT = "^0.3.7"
pyautogui = "^0.9.54"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
